# name: CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   test:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     environment: Testing
    
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       - name: Install dependencies
#         run: python -m pip install -r ./requirements.txt

#       - name: Set Atlas Cluster URI
#         env: 
#           ATLAS_URI: ${{ secrets.ATLAS_URI }}
#         run: echo "ATLAS_URI=$ATLAS_URI" > .env && echo "DB_NAME=pymongo_tutorial" >> .env

#       - name: Run tests
#         run: python -m pip install pytest && python -m pytest